(let ((EXE (qs "go env GOEXE")))
  (make
    ((append '("smake$(EXE)") (glob "*.go"))
     (sh "go fmt")
     (sh "go build")
     )
    ('("update")
     (touch "main.go")
     )
    ('("readme" "README.md")
     )
    ('("README.md" "_README.md" "Makefile.lsp")
       (sh "gmnlpp$(EXE) $< > \"$@\"")
     )
    ('("clean")
     (rm "smake$(EXE)~")
     )
  )
)
